"""domain model (F003 task 004)

Revision ID: 0003_domain_model
Revises: 0002_worker_queue
Create Date: 2026-07-17

Introduces the FreeTier Atlas catalogue / evidence domain model: the catalogue
(Provider, Category, Service, Offer), the immutable material history
(OfferVersion, Quota, RegionAvailability), the evidence provenance chain
(Source, Snapshot, Evidence), and the operational records (ChangeEvent, ScanRun,
ReviewItem). The table shapes are generated from the SQLAlchemy models in
``app.models`` (see ``migrations/env.py`` target_metadata), so ``alembic``
autogenerate / compare_metadata can detect drift.

``offer_version`` holds *immutable material offer facts*: a BEFORE UPDATE OR
DELETE trigger makes it append-only at the database level. New versions are
INSERTed; existing rows can never be modified or removed. ``downgrade`` drops
the trigger and function and then every domain table in dependency order,
leaving the 0001/0002 infrastructure tables untouched.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003_domain_model"
down_revision: str | None = "0002_worker_queue"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
        sa.UniqueConstraint("slug", name="uq_category_slug"),
    )
    op.create_table(
        "provider",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column(
            "official_domains",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_health", sa.Text(), nullable=True),
        sa.Column("completeness_score", sa.Numeric(), nullable=True),
        sa.Column("freshness_score", sa.Numeric(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider")),
        sa.UniqueConstraint("slug", name="uq_provider_slug"),
    )
    op.create_table(
        "service",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("provider_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("official_url", sa.Text(), nullable=True),
        sa.Column("deployment_model", sa.Text(), nullable=False),
        sa.Column(
            "portability_traits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "deployment_model IN ('managed', 'self_hosted')",
            name=op.f("ck_service_deployment_model_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_service_category_id_category"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["provider.id"],
            name=op.f("fk_service_provider_id_provider"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service")),
        sa.UniqueConstraint("provider_id", "canonical_name", name="uq_service_provider_id"),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("provider_id", sa.BigInteger(), nullable=True),
        sa.Column("adapter_type", sa.Text(), nullable=False),
        sa.Column("trust_level", sa.Text(), nullable=False),
        sa.Column("official", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=True),
        sa.Column("schedule", sa.Text(), nullable=True),
        sa.Column("parser_profile", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("health", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["provider.id"],
            name=op.f("fk_source_provider_id_provider"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
    )
    op.create_table(
        "offer",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("service_id", sa.BigInteger(), nullable=False),
        sa.Column("offer_type", sa.Text(), nullable=False),
        sa.Column("zero_cost_class", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("commercial_use_allowed", sa.Boolean(), nullable=True),
        sa.Column("personal_use_allowed", sa.Boolean(), nullable=True),
        sa.Column("requires_card", sa.Boolean(), nullable=True),
        sa.Column("has_paid_dependencies", sa.Boolean(), nullable=True),
        sa.Column("available_from", sa.Date(), nullable=True),
        sa.Column("available_until", sa.Date(), nullable=True),
        sa.Column("visibility", sa.Text(), server_default=sa.text("'public'"), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "offer_type IN ('always_free', 'recurring_quota', 'new_customer_credit', 'trial', 'startup_program', 'student_program', 'open_source_program', 'hackathon_promotion', 'personal_use_free', 'self_hosted_open_source', 'other')",  # noqa: E501
            name=op.f("ck_offer_offer_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'withdrawn', 'deprecated', 'unknown')",
            name=op.f("ck_offer_status_valid"),
        ),
        sa.CheckConstraint(
            "visibility IN ('public', 'private', 'unlisted')",
            name=op.f("ck_offer_visibility_valid"),
        ),
        sa.CheckConstraint(
            "zero_cost_class IN ('Z0_TRUE_FREE', 'Z1_BILLING_EXPOSURE', 'Z2_TEMPORARY_OR_CONDITIONAL', 'Z3_SELF_HOSTED_BUILDING_BLOCK', 'UNKNOWN')",  # noqa: E501
            name=op.f("ck_offer_zero_cost_class_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service.id"],
            name=op.f("fk_offer_service_id_service"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer")),
    )
    op.create_table(
        "scan_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'running'"), nullable=False),
        sa.Column("documents_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("candidates_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("changes_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("errors_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'failed', 'partial')",
            name=op.f("ck_scan_run_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_scan_run_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_run")),
    )
    op.create_table(
        "snapshot",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("content_location", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_snapshot_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_snapshot")),
    )
    op.create_table(
        "offer_version",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("offer_id", sa.BigInteger(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("offer_type", sa.Text(), nullable=False),
        sa.Column("zero_cost_class", sa.Text(), nullable=False),
        sa.Column(
            "material_facts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "offer_type IN ('always_free', 'recurring_quota', 'new_customer_credit', 'trial', 'startup_program', 'student_program', 'open_source_program', 'hackathon_promotion', 'personal_use_free', 'self_hosted_open_source', 'other')",  # noqa: E501
            name=op.f("ck_offer_version_offer_type_valid"),
        ),
        sa.CheckConstraint(
            "zero_cost_class IN ('Z0_TRUE_FREE', 'Z1_BILLING_EXPOSURE', 'Z2_TEMPORARY_OR_CONDITIONAL', 'Z3_SELF_HOSTED_BUILDING_BLOCK', 'UNKNOWN')",  # noqa: E501
            name=op.f("ck_offer_version_zero_cost_class_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offer.id"],
            name=op.f("fk_offer_version_offer_id_offer"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer_version")),
        sa.UniqueConstraint("offer_id", "version_number", name="uq_offer_version_offer_id"),
    )
    op.create_table(
        "region_availability",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("provider_id", sa.BigInteger(), nullable=False),
        sa.Column("offer_id", sa.BigInteger(), nullable=True),
        sa.Column("region_code", sa.Text(), nullable=False),
        sa.Column("free_available", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("residency", sa.Text(), nullable=True),
        sa.Column("data_plane_location", sa.Text(), nullable=True),
        sa.Column("control_plane_location", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offer.id"],
            name=op.f("fk_region_availability_offer_id_offer"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["provider.id"],
            name=op.f("fk_region_availability_provider_id_provider"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_region_availability")),
    )
    op.create_table(
        "review_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("scan_run_id", sa.BigInteger(), nullable=True),
        sa.Column("offer_id", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_conflict", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("candidate_facts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recommended_action", sa.Text(), nullable=True),
        sa.Column(
            "admin_disposition", sa.Text(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "admin_disposition IN ('pending', 'approved', 'rejected', 'deferred')",
            name=op.f("ck_review_item_admin_disposition_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offer.id"],
            name=op.f("fk_review_item_offer_id_offer"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_run.id"],
            name=op.f("fk_review_item_scan_run_id_scan_run"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_item")),
    )
    op.create_table(
        "change_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("offer_id", sa.BigInteger(), nullable=False),
        sa.Column("previous_version_id", sa.BigInteger(), nullable=True),
        sa.Column("new_version_id", sa.BigInteger(), nullable=True),
        sa.Column("change_type", sa.Text(), nullable=False),
        sa.Column("materiality", sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "publication_status", sa.Text(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "change_type IN ('added', 'modified', 'withdrawn', 'restored')",
            name=op.f("ck_change_event_change_type_valid"),
        ),
        sa.CheckConstraint(
            "materiality IN ('material', 'non_material', 'unknown')",
            name=op.f("ck_change_event_materiality_valid"),
        ),
        sa.CheckConstraint(
            "publication_status IN ('draft', 'published', 'withheld')",
            name=op.f("ck_change_event_publication_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["new_version_id"],
            ["offer_version.id"],
            name=op.f("fk_change_event_new_version_id_offer_version"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offer.id"],
            name=op.f("fk_change_event_offer_id_offer"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["previous_version_id"],
            ["offer_version.id"],
            name=op.f("fk_change_event_previous_version_id_offer_version"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_event")),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("offer_version_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("official", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column(
            "retrieved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("selector", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["offer_version_id"],
            ["offer_version.id"],
            name=op.f("fk_evidence_offer_version_id_offer_version"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshot.id"],
            name=op.f("fk_evidence_snapshot_id_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_evidence_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_table(
        "quota",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("offer_version_id", sa.BigInteger(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("reset_period", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("region_scope", sa.Text(), nullable=True),
        sa.Column("behaviour", sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
        sa.Column("exhaustion_behaviour", sa.Text(), nullable=False),
        sa.Column("retention_policy", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "behaviour IN ('hard', 'soft', 'unknown')", name=op.f("ck_quota_behaviour_valid")
        ),
        sa.CheckConstraint(
            "exhaustion_behaviour IN ('hard_stop', 'request_rejected', 'throttled', 'service_sleeps', 'read_only', 'deployment_blocked', 'site_disabled_until_reset', 'resource_reclaimed', 'data_deleted', 'automatic_billing', 'manual_upgrade_required', 'unknown')",  # noqa: E501
            name=op.f("ck_quota_exhaustion_behaviour_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["offer_version_id"],
            ["offer_version.id"],
            name=op.f("fk_quota_offer_version_id_offer_version"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quota")),
    )
    # ### end Alembic commands ###

    # offer_version holds immutable material offer facts: make it append-only.
    # A BEFORE UPDATE OR DELETE trigger rejects any mutation of an existing row;
    # new versions must be INSERTed.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION offer_version_immutable()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'offer_version rows are immutable (append-only); % is not permitted',
                TG_OP
                USING ERRCODE = 'restrict_violation';
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_offer_version_immutable
        BEFORE UPDATE OR DELETE ON offer_version
        FOR EACH ROW EXECUTE FUNCTION offer_version_immutable();
        """
    )


def downgrade() -> None:
    # Drop the append-only trigger/function before removing offer_version.
    op.execute("DROP TRIGGER IF EXISTS trg_offer_version_immutable ON offer_version;")
    op.execute("DROP FUNCTION IF EXISTS offer_version_immutable();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quota")
    op.drop_table("evidence")
    op.drop_table("change_event")
    op.drop_table("review_item")
    op.drop_table("region_availability")
    op.drop_table("offer_version")
    op.drop_table("snapshot")
    op.drop_table("scan_run")
    op.drop_table("offer")
    op.drop_table("source")
    op.drop_table("service")
    op.drop_table("provider")
    op.drop_table("category")
    # ### end Alembic commands ###
